#!/bin/bash

# Log session end event + extract gotchas + generate session summary

set -euo pipefail

# Skip if logging disabled
if [[ "${SKIP_LOGGING:-}" == "true" ]]; then
  exit 0
fi

# Read input from Copilot
INPUT=$(cat)

# Create logs directory if it doesn't exist
mkdir -p logs/copilot

# Extract timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TODAY=$(date -u +"%Y-%m-%d")
SESSION_ID=$(date -u +"%Y-%m-%d-%H%M")

# Log session end
echo "{\"timestamp\":\"$TIMESTAMP\",\"event\":\"sessionEnd\"}" >> logs/copilot/session.log

# --- Gotcha Capture (expanded keywords) ---
SESSION_LOG="logs/copilot/session.log"
PROMPTS_LOG="logs/copilot/prompts.log"
GOTCHA_FILE=".copilot/memories/repo/discovered-gotchas.md"

if [[ -f "$SESSION_LOG" ]]; then
  # Expanded keyword list: original + lesson/remember/note/important
  GOTCHAS=$(grep -i -E "gotcha:|trap:|pitfall:|watch out:|careful:|beware:|lesson:|remember:|note for future:|important:" "$SESSION_LOG" 2>/dev/null | tail -20 || true)

  if [[ -n "$GOTCHAS" ]]; then
    mkdir -p "$(dirname "$GOTCHA_FILE")"

    if [[ ! -f "$GOTCHA_FILE" ]]; then
      echo "# Discovered Gotchas" > "$GOTCHA_FILE"
      echo "" >> "$GOTCHA_FILE"
      echo "> Auto-captured from sessions. Review before promoting to org-level anti-patterns." >> "$GOTCHA_FILE"
      echo "" >> "$GOTCHA_FILE"
    fi

    echo "## $TIMESTAMP" >> "$GOTCHA_FILE"
    echo "" >> "$GOTCHA_FILE"
    echo "$GOTCHAS" | while IFS= read -r line; do
      echo "- $line" >> "$GOTCHA_FILE"
    done
    echo "" >> "$GOTCHA_FILE"

    # Promotion hint: if >5 entries exist, suggest org-level promotion
    GOTCHA_COUNT=$(grep -c "^- " "$GOTCHA_FILE" 2>/dev/null || echo "0")
    if [[ "$GOTCHA_COUNT" -gt 5 ]]; then
      echo "💡 $GOTCHA_COUNT gotchas accumulated — consider promoting common ones to org-level anti-patterns"
    fi
  fi
fi

# --- Session Summary Generation ---
SUMMARY_DIR=".copilot/memories/repo/session-summaries"
SUMMARY_FILE="$SUMMARY_DIR/$SESSION_ID.md"
mkdir -p "$SUMMARY_DIR"

# Count prompts from today's session
PROMPT_COUNT=0
if [[ -f "$PROMPTS_LOG" ]]; then
  PROMPT_COUNT=$(grep -c "$TODAY" "$PROMPTS_LOG" 2>/dev/null || echo "0")
fi

# Only generate summary if session had activity (>0 prompts)
if [[ "$PROMPT_COUNT" -gt 0 ]]; then
  # Detect modified files (git diff if available)
  CHANGED_FILES=""
  if command -v git &>/dev/null && git rev-parse --is-inside-work-tree &>/dev/null 2>&1; then
    CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null | head -20 || true)
  fi

  # Write session summary
  cat > "$SUMMARY_FILE" << EOF
# Session Summary — $SESSION_ID

- **Date**: $TODAY
- **Prompts**: $PROMPT_COUNT
- **Working Directory**: $(pwd)

## Files Changed

$(if [[ -n "$CHANGED_FILES" ]]; then echo "$CHANGED_FILES" | sed 's/^/- /'; else echo "_No git changes detected_"; fi)

## Gotchas Discovered

$(if [[ -n "${GOTCHAS:-}" ]]; then echo "$GOTCHAS" | sed 's/^/- /'; else echo "_None this session_"; fi)

## Open Questions

_Review and fill manually if needed._

---
*Auto-generated by session-logger hook*
EOF

  echo "📋 Session summary saved → $SUMMARY_FILE"
fi

# --- Session Handoff Artifact ---
# Provides a structured context-reset document for the next agent session
HANDOFF_FILE=".copilot/memories/repo/session-handoff.md"
TEMPLATE_DIR="$(dirname "$0")/templates"

# Only write handoff if session had activity
if [[ "$PROMPT_COUNT" -gt 0 ]]; then
  mkdir -p ".copilot/memories/repo"

  CHANGED_FILES_SECTION="_No git changes detected_"
  if [[ -n "${CHANGED_FILES:-}" ]]; then
    CHANGED_FILES_SECTION=$(echo "$CHANGED_FILES" | sed 's/^/- /')
  fi

  GOTCHAS_SECTION="_None this session_"
  if [[ -n "${GOTCHAS:-}" ]]; then
    GOTCHAS_SECTION=$(echo "$GOTCHAS" | sed 's/^/- /')
  fi

  # Build project name from git remote or directory
  PROJECT_NAME="$(basename "$(git rev-parse --show-toplevel 2>/dev/null || pwd)")"

  cat > "$HANDOFF_FILE" << EOF
# Session Handoff — $SESSION_ID

> **Purpose**: Structured artifact for context resets between agent sessions.
> The next agent reads this file at session start to resume work coherently.

- **Date**: $TODAY
- **Working Directory**: $(pwd)
- **Prompts This Session**: $PROMPT_COUNT
- **Project**: $PROJECT_NAME

---

## ✅ Completed This Session

$CHANGED_FILES_SECTION

---

## 🔄 In Progress / Next Steps

- [ ] _Review progress.md for remaining features_
- [ ] _Check open bugs section below before starting_

---

## 🐛 Open Bugs / Issues

- _None_ (update if issues were found during the session)

---

## 🔑 Key Decisions Made

- _See session summary at .copilot/memories/repo/session-summaries/$SESSION_ID.md_

---

## 💡 Gotchas Discovered

$GOTCHAS_SECTION

---

## 🔗 Context Pointers

| File | Contains |
|------|---------|
| \`.copilot/memories/repo/progress.md\` | Feature-level completion tracking |
| \`.copilot/memories/repo/discovered-gotchas.md\` | Accumulated gotchas |
| \`.copilot/memories/repo/knowledge-drift.md\` | Stale domain docs |
| \`/memories/session/chain-state.md\` | Orchestrator chain checkpoints |
| \`/memories/session/plan.md\` | Current feature plan |

---
*Auto-generated by session-logger hook on $TIMESTAMP*
EOF

  echo "🤝 Session handoff saved → $HANDOFF_FILE"
fi

# --- Retention: keep last 30 days of summaries ---
if [[ -d "$SUMMARY_DIR" ]]; then
  find "$SUMMARY_DIR" -name "*.md" -mtime +30 -delete 2>/dev/null || true
fi

echo "📝 Session end logged"
exit 0
