#!/bin/bash

# knowledge-drift/detect-drift.sh
# Runs at sessionEnd — detects source files changed during the session,
# maps them to their domain folder, and flags AGENTS.md as potentially stale.
# Output is appended to .copilot/memories/repo/knowledge-drift.md

set -euo pipefail

# Skip if disabled
if [[ "${SKIP_KNOWLEDGE_DRIFT:-}" == "true" ]]; then
  exit 0
fi

DRIFT_FILE=".copilot/memories/repo/knowledge-drift.md"
TIMESTAMP=$(date -u +"%Y-%m-%d")

# --- Determine changed files ---
# Try git diff against last commit; fall back to diff of working tree
CHANGED_FILES=""

if git rev-parse --git-dir >/dev/null 2>&1; then
  # Files changed since last commit (staged + unstaged + untracked source files)
  CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null || true)
  CHANGED_FILES+=$'\n'$(git diff --name-only --cached 2>/dev/null || true)

  # Also include files changed in the last commit if this is a fresh commit session
  LAST_COMMIT_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || true)
  CHANGED_FILES+=$'\n'"$LAST_COMMIT_FILES"
fi

# Deduplicate and remove empty lines
CHANGED_FILES=$(echo "$CHANGED_FILES" | sort -u | grep -v '^$' || true)

if [[ -z "$CHANGED_FILES" ]]; then
  # Nothing changed — nothing to flag
  exit 0
fi

# --- Filter to source files only (ignore docs, hooks, config noise) ---
SOURCE_FILES=$(echo "$CHANGED_FILES" | grep -E '\.(cs|ts|tsx|js|jsx|py|go|java|rb|php)$' | grep -v -E '(node_modules|dist|build|obj|bin|\.git|coverage|Migrations)' || true)

if [[ -z "$SOURCE_FILES" ]]; then
  exit 0
fi

# --- Map each source file to its domain folder ---
# A domain folder is the second path segment (e.g. src/Orders/... → Orders)
# Works for: src/Features/Orders, src/modules/orders, src/Orders, apps/orders, etc.

declare -A STALE_DOMAINS

while IFS= read -r file; do
  if [[ -z "$file" ]]; then
    continue
  fi

  # Strip leading ./
  file="${file#./}"

  # Extract domain: second meaningful path segment after common prefixes
  # e.g. src/Features/Orders/OrderService.cs  → Orders
  #      src/orders/hooks/useOrderQuery.ts     → orders
  #      apps/inventory/src/service.ts         → inventory
  #      Orders/OrderService.cs                → Orders (flat structure)

  DOMAIN=""

  if [[ "$file" == src/features/* ]] || [[ "$file" == src/Features/* ]]; then
    DOMAIN=$(echo "$file" | cut -d'/' -f3)
  elif [[ "$file" == src/modules/* ]]; then
    DOMAIN=$(echo "$file" | cut -d'/' -f3)
  elif [[ "$file" == src/pages/* ]]; then
    DOMAIN=$(echo "$file" | cut -d'/' -f3)
  elif [[ "$file" == src/domain/* ]] || [[ "$file" == src/Domain/* ]]; then
    DOMAIN=$(echo "$file" | cut -d'/' -f3)
  elif [[ "$file" == src/* ]]; then
    DOMAIN=$(echo "$file" | cut -d'/' -f2)
  elif [[ "$file" == apps/* ]] || [[ "$file" == libs/* ]] || [[ "$file" == packages/* ]]; then
    DOMAIN=$(echo "$file" | cut -d'/' -f2)
  else
    # Flat structure: first path segment
    DOMAIN=$(echo "$file" | cut -d'/' -f1)
  fi

  # Skip empty, dot-prefixed, or noise domains
  if [[ -z "$DOMAIN" ]] || [[ "$DOMAIN" == .* ]] || [[ "$DOMAIN" =~ ^(src|lib|test|tests|spec|__tests__|shared|common|utils|helpers|config|hooks|types|assets|styles|public|static)$ ]]; then
    continue
  fi

  # Collect changed files per domain
  if [[ -n "${STALE_DOMAINS[$DOMAIN]:-}" ]]; then
    STALE_DOMAINS[$DOMAIN]="${STALE_DOMAINS[$DOMAIN]}, $(basename "$file")"
  else
    STALE_DOMAINS[$DOMAIN]="$(basename "$file")"
  fi

done <<< "$SOURCE_FILES"

# --- Write drift entries ---
if [[ ${#STALE_DOMAINS[@]} -eq 0 ]]; then
  exit 0
fi

mkdir -p "$(dirname "$DRIFT_FILE")"

if [[ ! -f "$DRIFT_FILE" ]]; then
  cat > "$DRIFT_FILE" << 'EOF'
# Knowledge Drift Log

> Auto-generated by `knowledge-drift` hook at sessionEnd.
> Run `/knowledge-init --update` to refresh stale domain docs.
> Resolved entries are marked RESOLVED and can be pruned periodically.

EOF
fi

for DOMAIN in "${!STALE_DOMAINS[@]}"; do
  FILES="${STALE_DOMAINS[$DOMAIN]}"
  ENTRY="[$TIMESTAMP] STALE: $DOMAIN — $FILES"

  # Avoid duplicate entries for the same domain+date
  if ! grep -qF "[$TIMESTAMP] STALE: $DOMAIN" "$DRIFT_FILE" 2>/dev/null; then
    echo "$ENTRY" >> "$DRIFT_FILE"
    echo "⚠️  knowledge-drift: $DOMAIN docs may be stale ($FILES changed)"
  fi
done

# --- Prune old RESOLVED entries (older than 30 days) ---
if [[ -f "$DRIFT_FILE" ]]; then
  CUTOFF=$(date -u -d "30 days ago" +"%Y-%m-%d" 2>/dev/null || date -u -v-30d +"%Y-%m-%d" 2>/dev/null || true)
  if [[ -n "$CUTOFF" ]]; then
    # Remove RESOLVED lines older than cutoff (simple date comparison)
    grep -v "^\[20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]\] RESOLVED:" "$DRIFT_FILE" > "$DRIFT_FILE.tmp" 2>/dev/null || true
    if [[ -s "$DRIFT_FILE.tmp" ]]; then
      mv "$DRIFT_FILE.tmp" "$DRIFT_FILE"
    else
      rm -f "$DRIFT_FILE.tmp"
    fi
  fi
fi

exit 0
